//Default
export const LOADING_START = 'LOADING_START';
export const LOADING_END = 'LOADING_END';

// Modal
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

//Auth
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const RESET_PWD_REQUEST = 'RESET_PWD_REQUEST';
export const RESET_PWD_SUCCESS = 'RESET_PWD_SUCCESS';
export const RESET_PWD_FAILED = 'RESET_PWD_FAILED';
export const LOGOUT = 'LOGOUT';
export const CLRERR = 'CLRERR'

//assets
export const GET_ASSETS_REQUEST = 'GET_ASSETS_REQUEST';
export const GET_ASSETS_SUCCESS = 'GET_ASSETS_SUCCESS';
export const GET_ASSETS_FAILED = 'GET_ASSETS_FAILED';

export const CREATE_ASSETS_REQUEST = 'CREATE_ASSETS_REQUEST';
export const CREATE_ASSETS_SUCCESS = 'CREATE_ASSETS_SUCCESS';
export const CREATE_ASSETS_FAILED = 'CREATE_ASSETS_FAILED';

export const EDIT_ASSETS_REQUEST = 'EDIT_ASSETS_REQUEST';
export const EDIT_ASSETS_SUCCESS = 'EDIT_ASSETS_SUCCESS';
export const EDIT_ASSETS_FAILED = 'EDIT_ASSETS_FAILED';

export const DELETE_ASSETS_REQUEST = 'DELETE_ASSETS_REQUEST';
export const DELETE_ASSETS_SUCCESS = 'DELETE_ASSETS_SUCCESS';
export const DELETE_ASSETS_FAILED = 'DELETE_ASSETS_FAILED';

// Income
export const GET_INCOME_REQUEST = 'GET_INCOME_REQUEST';
export const GET_INCOME_SUCCESS = 'GET_INCOME_SUCCESS';
export const GET_INCOME_FAILED = 'GET_INCOME_FAILED';

export const CREATE_INCOME_REQUEST = 'CREATE_INCOME_REQUEST';
export const CREATE_INCOME_SUCCESS = 'CREATE_INCOME_SUCCESS';
export const CREATE_INCOME_FAILED = 'CREATE_INCOME_FAILED';

export const EDIT_INCOME_REQUEST = 'EDIT_INCOME_REQUEST';
export const EDIT_INCOME_SUCCESS = 'EDIT_INCOME_SUCCESS';
export const EDIT_INCOME_FAILED = 'EDIT_INCOME_FAILED';

export const DELETE_INCOME_REQUEST = 'DELETE_INCOME_REQUEST';
export const DELETE_INCOME_SUCCESS = 'DELETE_INCOME_SUCCESS';
export const DELETE_INCOME_FAILED = 'DELETE_INCOME_FAILED';


// expenditure
export const GET_EXPENDITURE_REQUEST = 'GET_EXPENDITURE_REQUEST';
export const GET_EXPENDITURE_SUCCESS = 'GET_EXPENDITURE_SUCCESS';
export const GET_EXPENDITURE_FAILED = 'GET_EXPENDITURE_FAILED';

export const CREATE_EXPENDITURE_REQUEST = 'CREATE_EXPENDITURE_REQUEST';
export const CREATE_EXPENDITURE_SUCCESS = 'CREATE_EXPENDITURE_SUCCESS';
export const CREATE_EXPENDITURE_FAILED = 'CREATE_EXPENDITURE_FAILED';

export const EDIT_EXPENDITURE_REQUEST = 'EDIT_EXPENDITURE_REQUEST';
export const EDIT_EXPENDITURE_SUCCESS = 'EDIT_EXPENDITURE_SUCCESS';
export const EDIT_EXPENDITURE_FAILED = 'EDIT_EXPENDITURE_FAILED';

export const DELETE_EXPENDITURE_REQUEST = 'DELETE_EXPENDITURE_REQUEST';
export const DELETE_EXPENDITURE_SUCCESS = 'DELETE_EXPENDITURE_SUCCESS';
export const DELETE_EXPENDITURE_FAILED = 'DELETE_EXPENDITURE_FAILED';

// Creditor
export const GET_CREDITOR_REQUEST = 'GET_CREDITOR_REQUEST';
export const GET_CREDITOR_SUCCESS = 'GET_CREDITOR_SUCCESS';
export const GET_CREDITOR_FAILED = 'GET_CREDITOR_FAILED';

export const CREATE_CREDITOR_REQUEST = 'CREATE_CREDITOR_REQUEST';
export const CREATE_CREDITOR_SUCCESS = 'CREATE_CREDITOR_SUCCESS';
export const CREATE_CREDITOR_FAILED = 'CREATE_CREDITOR_FAILED';

export const EDIT_CREDITOR_REQUEST = 'EDIT_CREDITOR_REQUEST';
export const EDIT_CREDITOR_SUCCESS = 'EDIT_CREDITOR_SUCCESS';
export const EDIT_CREDITOR_FAILED = 'EDIT_CREDITOR_FAILED';

export const DELETE_CREDITOR_REQUEST = 'DELETE_CREDITOR_REQUEST';
export const DELETE_CREDITOR_SUCCESS = 'DELETE_CREDITOR_SUCCESS';
export const DELETE_CREDITOR_FAILED = 'DELETE_CREDITOR_FAILED';

//GET Types
export const GET_TYPES_REQUEST = 'GET_TYPES_REQUEST';
export const GET_TYPES_SUCCESS = 'GET_TYPES_SUCCESS';
export const GET_TYPES_FAILED = 'GET_TYPES_FAILED';

//GET NetWorth
export const GET_NET_WORTH_REQUEST = 'GET_NET_WORTH_REQUEST';
export const GET_NET_WORTH_SUCCESS = 'GET_NET_WORTH_SUCCESS';
export const GET_NET_WORTH_FAILED = 'GET_NET_WORTH_FAILED';

//GET Cash Flow
export const GET_CASH_FLOW_REQUEST = 'GET_CASH_FLOW_REQUEST';
export const GET_CASH_FLOW_SUCCESS = 'GET_CASH_FLOW_SUCCESS';
export const GET_CASH_FLOW_FAILED = 'GET_CASH_FLOW_FAILED';

//GET Dashboard
export const GET_DASHBOARD_DATA_REQUEST = 'GET_DASHBOARD_DATA_REQUEST';
export const GET_DASHBOARD_DATA_SUCCESS = 'GET_DASHBOARD_DATA_SUCCESS';
export const GET_DASHBOARD_DATA_FAILED = 'GET_DASHBOARD_DATA_FAILED';

//Dashboard
export const GET_CUSTOMER_REQUEST = 'GET_CUSTOMER_REQUEST';
export const GET_CUSTOMER_SUCCESS = 'GET_CUSTOMER_SUCCESS';
export const GET_CUSTOMER_FAILED = 'GET_CUSTOMER_FAILED';

export const EDIT_CUSTOMER_REQUEST = 'EDIT_CUSTOMER_REQUEST';
export const EDIT_CUSTOMER_SUCCESS = 'EDIT_CUSTOMER_SUCCESS';
export const EDIT_CUSTOMER_FAILED = 'EDIT_CUSTOMER_FAILED';